### ISSUE TITLE
Use `os#homedir` instead of hardcoding paths in `makeBookmarksMenu`

### ISSUE THREAD

**Issue by parkerault** [CrossR/dotfiles#5]
https://github.com/CrossR/dotfiles/blob/1378bb94bfb3363e27b91f9b3c5a62540f79f9c6/oni/config.tsx#L20

Hey Ryan, instead of hard coding your paths for different machines, you can use:
```js
import { homedir } from "os";
const homeDirectory = homedir();
const gitProjects = join([homeDirectory], "Documents\\Git");
```
...and I _think_ it will work across your different machines as long as you use the same folder structure. I don't have a windows box to test it on, but it works on my mac. Cheers!

**Comment by parkerault** [comment]
Are you using the master branch for your oni build? I built from the latest master and `workspace.openFolder` is undefined. Sorry to bug you so much about this, but it's a snazzy feature and it _almost_ works 😄. I would even go so far as to say it should be one of the default plugins.

![image](https://user-images.githubusercontent.com/78856/37873643-7215d066-2fe6-11e8-88ae-848b2d5c9561.png)
```
import * as React from "/Users/enolammt/Documents/projects/oni/node_modules/react"
import * as Oni from "/Users/enolammt/Documents/projects/oni/node_modules/oni-api"

import { existsSync, lstatSync, readdirSync } from "fs";
import { join, parse } from "path";
import { homedir } from "os";

export const activate = (oni: Oni.Plugin.Api) => {
  const {
    editors,
    input,
    menu,
    workspace
  } = oni;
  console.log("config activated")
  // Add a bookmarks menu to swap easily between different workspaces.
  // Dynamically generated from my Git folder.
  const makeBookmarksMenu = () => {
    const homeDirectory = homedir();

    let projectsDir = join(homeDirectory, "Documents/projects");

    const isDirectory = (source) => {
      return lstatSync(source).isDirectory()
    };
    const getDirectories = (source) => {
      return readdirSync(source).map(name => join(source, name)).filter(isDirectory)
    };

    const projects = getDirectories(projectsDir);

    let menuItems = projects.map((directory) => ({
      icon: "bookmark",
      detail: directory,
      label: parse(directory).base,
    });

    menuItems.unshift({
      icon: "folder-open",
      detail: "Set a folder as the workspace for Oni",
      label: "Open Folder",
    });

    const bookmarkMenu = menu.create();
    bookmarkMenu.show();
    bookmarkMenu.setItems(menuItems);

    bookmarkMenu.onItemSelected.subscribe(menuItem => {
      if (menuItem && menuItem.label !== "Open Folder") {
        workspace.changeDirectory(menuItem.detail);
      } else if (menuItem && menuItem.label === "Open Folder") {
        workspace.openFolder();
      }
    })
  }

  input.bind("<s-c-w>", makeBookmarksMenu)
  input.bind("<f8>", "markdown.togglePreview")
}
```

**Comment by CrossR** [comment]
I'm on the latest Master too... I'm getting the same warning, but it looks like the functionality still works for me. Is that not the case for you? 

![image](https://user-images.githubusercontent.com/10038688/37874352-4df908c6-3025-11e8-8de8-ff924777b018.png)

But I still get

![image](https://user-images.githubusercontent.com/10038688/37874386-d4a9626c-3025-11e8-8a8f-aa2df0029cc4.png)

At a guess, its because `openFolder` isn't actually exposed by the API, I just know its part of that object and am calling it anyways. I'll stick a link to this in discord and see if Bryphe knows anything more, but I'm assuming that is the case.

**Comment by parkerault** [comment]
In my case selecting any of the directories doesn't open the workspace, but the "Open Folder" link does work.

**Comment by CrossR** [comment]
What error are you getting?

You can use the built in dev tools to debug the config.js actually, which may help.

EDIT: Your code works fine for me...maybe its a path issue not on Windows?

**Comment by parkerault** [comment]
@CrossR Actually it started working after a few reloads! No idea why, but it's all good now, so thanks!!!

**Comment by CrossR** [comment]
For my own reference:

* This menu (or some form) is now in Oni itself, though has a few improvements I'd like mainly around globbing so I can easily swap to it.
* For the OS detection, I ended up going with an env var, since I needed it across a few languages and configs.
